---

- hosts: all
  become: true
  tasks:

    - name: Update repository index
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: latest

    - name: Install maven
      apt:
        name: maven
        state: latest
